### ISSUE TITLE
Encryption Attribute Not Included in Item::toArray()

### ISSUE THREAD

**Issue by mah484** [illuminatech/config#16]
### What steps will reproduce the problem?
Call \Illuminatech\Config\PersistentRepository::getItems()->toArray()

### What is the expected result?
Returns an array with 'encrypt' attribute.

### What do you get instead?
An array without the encrypt attribute.

### Additional info
This makes the solution provided [here](https://github.com/illuminatech/config/issues/15) invalid.

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.3.1
| Laravel Framework Version | 9.16.0
| PHP version               | 8.1.7
| Operating system          | CentOS 7.9

**Comment by klimov-paul** [comment]
Resolved by commit c4ed6d42b565635d67dc990697c80f6b954600c0
