### ISSUE TITLE
Still problem with arrays passed as keys

### ISSUE THREAD

**Issue by drbyte** [illuminatech/config#3]
The issue I was trying to fix in #2 still continues. The fix I proposed works fine, but doing it in userland requires a bunch of hacks to overload a bunch of package methods. It'd be preferable for the package to just do it itself.

In this particular case it's iterating over a config that was dynamically created by hyn/multi-tenant, but barfs when it finds it to be an array:

<img width="1556" alt="Image 2019-06-13 at 9 24 18 AM" src="https://user-images.githubusercontent.com/404472/59436373-7e5efb00-8dbd-11e9-8add-7b6db2ffbd19.png">

**Comment by klimov-paul** [comment]
Resolved by commit 780d3e2260792c07933d756d21c47facb6773331

**Comment by drbyte** [comment]
Thanks. That works. :)

**Comment by drbyte** [comment]
Hmmm ... while that change stops the error message, this package seems to be preventing that same config value from passing through properly.

I realize this isn't the support area for the multitenant package I'm using, removing your package leaves the multitenant package working properly. So I'm trying to sort out the intersection and figure out where the fix needs to be.

I think this package is incorrectly filtering out (or not passing forward) some config entries ... perhaps for types it doesn't account for. I'm guessing maybe your `setItems()` method needs to account for more cases?

In this scenario, it's still the same `tenant` filesystem config entry I posted about above.

`dd(Storage::disk('tenant');` gives:

```text
InvalidArgumentException
Driver [] is not supported.
```
... which tells me the key and/or its sub-properties are missing.

I posted more info over on the other package repo, but I think the problem isn't on their end.
https://github.com/tenancy/multi-tenant/issues/813

Would you prefer another Issue be opened for this?
