### ISSUE TITLE
Changing setting to be encrypted gives payload error

### ISSUE THREAD

**Issue by drbyte** [illuminatech/config#6]
### What steps will reproduce the problem?
Define a non-encrypted setting, and persist it.
Then change the properties to set `'encrypt' => true`.
Now attempt to read persisted values (ie: load any page in the app).

### What is the expected result?
Expected no app errors.

### What do you get instead?
The following error occurs, presumably because it's assuming the existing persisted setting is already encrypted.
```text
[2019-07-10 15:31:04] local.ERROR: The payload is invalid. 
{"userId":123,
"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The payload is invalid. 
at vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:195)"
} []
```

### Additional info

| Q                         | A
| ------------------------- | ---
| This Package Version      | 1.0.2
| Laravel Framework Version | 5.8.28
| PHP version               | 7.3.6

### Workaround
The only (and unfriendly) workaround appears to be to manually delete the setting from persisted storage, then run the app and collect the setting value via the app and have the app save it "fresh".

**Comment by klimov-paul** [comment]
Resolved by commit 545c9ed94ba527f8835f05a5f0ba94a1fd919771
Thank you for the reporting.
